---
- name: "Copy build to server"
  become: true
  copy:
    src: "{{ item }}"
    dest: /opt/udapeople
  with_fileglob:
    - /root/project/backend/dist/*


- name: "Start Application"
  become: true
  shell: "pm2 start /opt/udapeople/main.js"