---

- name: Creates Aplication Root
  become: true
  file:
    path: /opt/udapeople/
    state: directory

- name: "Copy build to server"
  become: true
  unarchive:
    src: /root/project/backend/build.zip
    dest: /opt/udapeople

- name: "Start Application"
  become: true
  shell: "pm2 start /opt/udapeople/main.js"