---

- name: Creates Aplication Root
  become: true
  file:
    path: /opt/udapeople/
    state: directory

- name: "Copy build to server"
  become: true
  unarchive:
    src: /root/project/backend.zip
    dest: /opt/udapeople

- name: "Build from sources"
  become: true
  shell: |
    cd /opt/udapeople/backend
    npm i
    npm run build

- name: "Start Application"
  become: true
  shell: |
    chmod -R 777 /opt/udapeople
    cd /opt/udapeople/backend/dist/
    pm2 start main.js --update-env

  environment:
    ENVIRONMENT: 'PRODUCTION'
    TYPEORM_CONNECTION: 'POSTGRES'
    TYPEORM_ENTITIES: './src/modules/domain/**/*.entity.ts'
    TYPEORM_HOST: "{{lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: "{{lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{lookup('env', 'TYPEORM_DATABASE')}}"

