---
- name: "Copy build to server"
  become: true
  synchronize:
    src: /root/project/backend/dist
    dest: /opt/udapeople

- name: "Start Application"
  become: true
  shell: "pm2 start /opt/udapeople/main.js"