version: 2.1

defaults: &nodeEnv
  docker:
    - image: circleci/node:13.8.0

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      test:
        type: string
        default: none 
    steps:
      - revert-migrations
      - run:
          name: Destroy backend
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name udaPeople-Backend-$CIRCLE_WORKFLOW_ID
      - run:
          name: Destroy frontend
          when: on_fail
          command: |
            aws s3 rm s3://udapeople-$CIRCLE_WORKFLOW_ID --recursive
            aws cloudformation delete-stack --stack-name udaPeople-Frontend-$CIRCLE_WORKFLOW_ID
            curl --request POST --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel --header "Circle-Token: ${CIRCLE_TOKEN}"

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      test:
        type: string
        default: none    
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            SUCCESS=$(curl -H "token: b994e046-2a53-4a93-80cf-feb669a7ec9b" --request GET https://api.memstash.io/values/success)
            if(( $SUCCESS==1 ));
            then
               cd root/project/backend
               npm i
               npm run migrations:revert
            fi
            
jobs:
  build-frontend:
    <<: *nodeEnv
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
              cd frontend
              npm i
              npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    <<: *nodeEnv
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm i
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
      - persist_to_workspace:
           root: ~/
           paths:
              - project/backend/dist

  test-frontend:
    <<: *nodeEnv
    steps:
      - checkout
      - restore_cache:
          keys: [ frontend-build ]
      - run:
          name: Front-end test
          command: |
            cd frontend
            npm i
            npm run test
#      - save_cache:
#          paths: [ frontend/node_modules ]
#          key: frontend-test
                
  test-backend:
    <<: *nodeEnv
    steps:
      - checkout
      - restore_cache:
         keys: [ backend-build ]
      - run:
          name: Backend test
          command: |
            cd backend
            npm i
            npm run test
#      - save_cache:
#            paths: [ backend/node_modules ]
#            key: backend-test
            
  scan-frontend:
    <<: *nodeEnv
    steps:
    - checkout
    - restore_cache:
        keys: [ backend-build ]
    - run:
        name: Frontend scan
        command: |
          cd frontend
          npm i
          npm audit fix --audit-level=critical --force

  scan-backend:
    <<: *nodeEnv
    steps:
      - checkout
      - restore_cache:
          keys: [ backend-build ]
      - run:
          name: Backend scan
          command: |
            cd backend
            npm i
            npm audit fix --audit-level=critical --force

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
#      # Checkout code from git
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/backend.yml \
            --tags project=hhUdaPeopleBE \
            --stack-name "udaPeople-Backend-$CIRCLE_WORKFLOW_ID" \
            --parameter-overrides ID=$CIRCLE_WORKFLOW_ID
      - run:
          name: get backend public-ip
          command: |
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters Name=tag:Name,Values=backend-$CIRCLE_WORKFLOW_ID --output text > backend-host
            echo BackenIP: "$(<backend-host)"
            curl -H "Content-Type: text/plain" -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request PUT --data @backend-host  https://api.memstash.io/values/url
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
            --template-file .circleci/files/frontend.yml \
            --tags project=hhUdaPeopleFE \
            --stack-name "udaPeople-Frontend-$CIRCLE_WORKFLOW_ID" \
            --parameter-overrides ID=$CIRCLE_WORKFLOW_ID
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            cd .circleci/ansible/
            echo [web]  > inventory.txt
            curl -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request GET https://api.memstash.io/values/url >> inventory.txt
            yum install -y tar
            yum install -y gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - project/.circleci/ansible/inventory.txt
      - destroy-environment

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["35:c6:27:51:f1:fc:09:3e:bb:cc:1c:b8:4b:91:d6:0e"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml
      - run:
          name: Prepare Rollback
          when: on_fail
          command: |
            pip3 install awscli
      - destroy-environment



  run-migrations:
    <<: *nodeEnv
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            cd backend
            npm i
            npm run migrations | tee migrating.txt

      - run:
          name: Send migration results to memstash
          command: |
            cd backend
            if grep -Fxq "Migration AddEmployee1555722583168 has been executed successfully" output.txt;
            then
            curl -H "Content-Type: text/plain" -H "token: b994e046-2a53-4a93-80cf-feb669a7ec9b" --request PUT --data "1" https://api.memstash.io/values/success;
            else
            curl -H "Content-Type: text/plain" -H "token: b994e046-2a53-4a93-80cf-feb669a7ec9b" --request PUT --data "0" https://api.memstash.io/values/success;
            fi
#      - destroy-environment

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
           name: Install dependencies
           command: |
             curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
             yum install -y nodejs
      - run:
          name: Get backend url
          command: |
            BACKEND_IP=$(curl -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request GET https://api.memstash.io/values/url)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"
      - run:
          name: Deploy frontend objects
          command: |
            BACKEND_IP=$(curl -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request GET https://api.memstash.io/values/url)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"
            cd frontend
            npm i
            npm run build
            aws s3 cp ./dist s3://udapeople-$CIRCLE_WORKFLOW_ID/ --recursive
      - destroy-environment

                    
  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["35:c6:27:51:f1:fc:09:3e:bb:cc:1c:b8:4b:91:d6:0e"]
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            apk add --update nodejs nodejs-npm
            apk add --update tar gzip

      - run:
          name: Build Backend
          command: |
            cd backend
            npm i
            npm run build
      - run:
          name: zip sources
          command: |
            tar czf backend.zip backend/*
      - run:
            name: deploy backend
            working_directory: ./.circleci/ansible
            command: |
              ansible-playbook -i inventory.txt deploy-backend.yml
      - run:
          name: Prepare Rollback
          when: on_fail
          command: |
            pip3 install awscli
      - destroy-environment



  smoke-test:
     docker:
      - image: python:3.7-alpine3.11
     steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update curl
            pip3 install awscli
      - run:
          name: Get backend url
          command: |
            BACKEND_IP=$(curl -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request GET https://api.memstash.io/values/url)
      - run:
          name: Backend smoke test.
          command: |
            BACKEND_IP=$(curl -H "token: e14ce597-d428-4f67-acb8-27c8e10191ca" --request GET https://api.memstash.io/values/url)
            echo $BACKEND_IP
 #           curl https://$BACKEND_IP:3030/api/status
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website.eu-central-1.amazonaws.com"
            if curl -s ${URL} | grep "Welcome"
            then
            return 0
            else
            return 1
            fi
      - destroy-environment

  cloudfront-update:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pwd
      - run:
          name: Update cloudfront distribution
          command: |
            aws cloudformation update-stack --stack-name udaPeople \
            --template-body file://.circleci/files/cloudfront.yml \
            --parameters ParameterKey=WorkflowID,ParameterValue=$CIRCLE_WORKFLOW_ID
      - destroy-environment

  cleanup:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Find and delete old stacks
          command: |

            export OldWorkflowID=$(aws cloudformation \
            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
            --no-paginate --output text)
            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
            echo ${OldWorkflowID}
            echo $STACKS
            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
            then
              echo Removing old stack ${OldWorkflowID}
              aws cloudformation delete-stack --stack-name udaPeople-Frontend-$OldWorkflowID 
              aws s3 rm s3://udapeople-$OldWorkflowID --recursive
              aws cloudformation delete-stack --stack-name udaPeople-Backend-$OldWorkflowID
            fi         

workflows:
  default:
    jobs:
#      - build-frontend
#      - build-backend
#      - test-frontend:
#          requires: [build-frontend]
#      - test-backend:
#          requires: [build-backend]
#      - scan-backend:
#          requires: [build-backend]
#      - scan-frontend:
#          requires: [build-frontend]
      - deploy-infrastructure:
#            requires: [test-frontend, test-backend, scan-frontend, scan-backend]
             filters:
               branches:
                 only: [main]
      - configure-infrastructure:
             requires: [deploy-infrastructure]
      - run-migrations:
             requires: [configure-infrastructure]
      - deploy-frontend:
             requires: [run-migrations]
      - deploy-backend:
            requires: [run-migrations]
      - smoke-test:
            requires: [deploy-backend, deploy-frontend]
      - cloudfront-update:
            requires: [smoke-test]
      - cleanup:
            requires: [cloudfront-update]
